server:
  port: 8070
  
 # Register with Eureka Service Registry
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka

# Expose all actuator end points 
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
  endpoint:
    gateway:
      enabled: true
# Configuration for zipkin tracing starts here
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/
#  tracing:
#    sampling:
#      probability: 1.0
# Configuration for zipkin tracing ends here        

# Gateway routing configuration starts here    
spring:
  application:
    name: NAV-CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: NAV-DEPARTMENT-SERVICE
          uri: lb://NAV-DEPARTMENT-SERVICE
          predicates:
            - Path=/deptApi/v1/**
          filters:
            - name: CircuitBreaker
              args:
                name: NAV-DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 10
          
          
        - id: NAV-EMPLOYEE-SERVICE
          uri: lb://NAV-EMPLOYEE-SERVICE
          predicates:
            - Path=/empApi/v1/**
          filters:
            - name: CircuitBreaker
              args:
                name: NAV-EMPLOYEE-SERVICE
                fallbackuri: forward:/employeeServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 10


